{{- if .Values.irsa.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-pod-identity-agent.fullname" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.service_account.role_arn }}
    {{- with .Values.irsa.service_account.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}