{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-pod-identity-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-pod-identity-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
      name: http
  selector:
    matchLabels:
      {{- include "eks-pod-identity-agent.selectorLabels" . | nindent 6 }}
{{-  end }}