{{- if .Values.irsa.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-pod-identity-agent.fullname" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.service_account.role_arn }}
    {{- with .Values.irsa.service_account.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.irsa.cluster_role.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eks-pod-identity-agent.fullname" . }}
rules:
{{- if .Values.irsa.cluster_role.permissions.serviceaccounts.verbs }}
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: {{ .Values.irsa.cluster_role.permissions.serviceaccounts.verbs }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eks-pod-identity-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eks-pod-identity-agent.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "eks-pod-identity-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end -}}